spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userService
    username: postgres
    password: Passw0rd
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  application:
    name: user-service

server:
  port: 8081