spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userService
    username: postgres
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  application:
    name: user-service

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET:defaultsecretfordevonly}
  expiration: ${JWT_EXPIRATION:86400000}

admin:
  email: ${ADMIN_EMAIL:admin@financehub.com}
  password: ${ADMIN_PASSWORD:Admin1!}
  firstName: ${ADMIN_FIRSTNAME:System}
  lastName: ${ADMIN_LASTNAME:Admin}
